# In Class Activity April 14th, 2026

In [2]:
!pip install optuna

zsh:1: command not found: pip

### Importing libraries, preparing data, initial EDA

In [3]:
# importing libraries (feel free to add more if you want to explore other things)
import numpy as np
import pandas as pd
import sweetviz as sv
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.model_selection import RandomizedSearchCV, StratifiedKFold
from xgboost import XGBClassifier
from sklearn.metrics import f1_score, accuracy_score, classification_report
import optuna

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [4]:
# importing data
adult = pd.read_csv('../Data/adult.csv')
adult.head(20)

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K
5,34,Private,198693,10th,6,Never-married,Other-service,Not-in-family,White,Male,0,0,30,United-States,<=50K
6,29,?,227026,HS-grad,9,Never-married,?,Unmarried,Black,Male,0,0,40,United-States,<=50K
7,63,Self-emp-not-inc,104626,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,3103,0,32,United-States,>50K
8,24,Private,369667,Some-college,10,Never-married,Other-service,Unmarried,White,Female,0,0,40,United-States,<=50K
9,55,Private,104996,7th-8th,4,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,10,United-States,<=50K
10,65,Private,184454,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,6418,0,40,United-States,>50K
11,36,Federal-gov,212465,Bachelors,13,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,0,40,United-States,<=50K
12,26,Private,82091,HS-grad,9,Never-married,Adm-clerical,Not-in-family,White,Female,0,0,39,United-States,<=50K
13,58,?,299831,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,35,United-States,<=50K
14,48,Private,279724,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,3103,0,48,United-States,>50K
15,43,Private,346189,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,50,United-States,>50K
16,20,State-gov,444554,Some-college,10,Never-married,Other-service,Own-child,White,Male,0,0,25,United-States,<=50K
17,43,Private,128354,HS-grad,9,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,30,United-States,<=50K
18,37,Private,60548,HS-grad,9,Widowed,Machine-op-inspct,Unmarried,White,Female,0,0,20,United-States,<=50K
19,40,Private,85019,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,45,?,>50K

In [5]:
# initial EDA with sweetviz
report = sv.analyze(adult)
report.show_html('sweet_report_04_14.html')

# you are welcome to replace this cell with your own EDA, but make sure to include
# some visualizations and insights about the data

adult.isnull().sum()

Done! Use 'show' commands to display/save.   |██████████| [100%]   00:00 -> (00:00 left)

Report sweet_report_04_14.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

age                0
workclass          0
fnlwgt             0
education          0
educational-num    0
marital-status     0
occupation         0
relationship       0
race               0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
native-country     0
income             0
dtype: int64

In [6]:
adult.dtypes

age                int64
workclass            str
fnlwgt             int64
education            str
educational-num    int64
marital-status       str
occupation           str
relationship         str
race                 str
gender               str
capital-gain       int64
capital-loss       int64
hours-per-week     int64
native-country       str
income               str
dtype: object

### In the markdown cell below describe what you learned from your EDA and how it will inform your modeling decisions

I learned that we have null values and also many categorical values along with numerical. However there seems to be a lot of categorical variables so I am thinking about potentually using catboost as a preliminary model. There is also class imbalance for our target variable so we need to take that into account

### Data Preprocessing (minimal) and Baseline Model

In [7]:
# data cleaning and preprocessing

# changing ? to NaN
adult = adult.replace('?', np.nan)

#education and education num are redundant, so we can drop one of them
adult = adult.drop('education', axis=1)

# target variable is income with 2 levels, so we can encode it as 0 and 1
adult['income'] = adult['income'].apply(lambda x: 1 if x == '>50K' else 0)

# change dtype categorical variables to category
categorical_cols = adult.select_dtypes(include='object').columns
adult[categorical_cols] = adult[categorical_cols].astype('category')


adult.head(20)

/var/folders/kk/czyhbh5961ggwtk14x632d900000gq/T/ipykernel_80624/2764229057.py:13: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = adult.select_dtypes(include='object').columns

,age,workclass,fnlwgt,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,0
1,38,Private,89814,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,0
2,28,Local-gov,336951,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,1
3,44,Private,160323,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,1
4,18,NaN,103497,10,Never-married,NaN,Own-child,White,Female,0,0,30,United-States,0
5,34,Private,198693,6,Never-married,Other-service,Not-in-family,White,Male,0,0,30,United-States,0
6,29,NaN,227026,9,Never-married,NaN,Unmarried,Black,Male,0,0,40,United-States,0
7,63,Self-emp-not-inc,104626,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,3103,0,32,United-States,1
8,24,Private,369667,10,Never-married,Other-service,Unmarried,White,Female,0,0,40,United-States,0
9,55,Private,104996,4,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,10,United-States,0
10,65,Private,184454,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,6418,0,40,United-States,1
11,36,Federal-gov,212465,13,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,0,40,United-States,0
12,26,Private,82091,9,Never-married,Adm-clerical,Not-in-family,White,Female,0,0,39,United-States,0
13,58,NaN,299831,9,Married-civ-spouse,NaN,Husband,White,Male,0,0,35,United-States,0
14,48,Private,279724,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,3103,0,48,United-States,1
15,43,Private,346189,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,50,United-States,1
16,20,State-gov,444554,10,Never-married,Other-service,Own-child,White,Male,0,0,25,United-States,0
17,43,Private,128354,9,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,30,United-States,0
18,37,Private,60548,9,Widowed,Machine-op-inspct,Unmarried,White,Female,0,0,20,United-States,0
19,40,Private,85019,16,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,45,NaN,1

In [8]:
# defining features and target variable
X = adult.drop('income', axis=1)
y = adult['income']

# splitting data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True, 
                                                    random_state=42, stratify=y)

In [9]:
# building xgboost default model and evaluating with stratified k-fold cross validation
xgb_cv = XGBClassifier(enable_categorical=True, random_state=42)
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
cv_scores = cross_val_score(xgb_cv, X, y, cv=skf, scoring='f1')
print(f'Cross-validated F1 scores: {cv_scores}')
print(f'Mean F1 score: {cv_scores.mean()}')

Cross-validated F1 scores: [0.70680507 0.70892566 0.70898981 0.72424942 0.71086556]
Mean F1 score: 0.7119671046056588

### Use the markdown cell below to describe your baseline model performance and how you will try to improve it

The model has no tuning so that is something I will look into. Also I will use the scale pos weight to account for class imbalance.

### Model feature exploration

In the code cell below, explore different features of XGBoost and how they work (e.g. scale_pos_weight, max_depth, learning_rate).
Use stratified k-fold cross or repeated stratified k-fold cross validation with your model building. 
You should explore at least 3 different features of XGBoost.
Identify the model that performs best.

In [10]:
# your code here
scale_pos_weight = 1.0
max_depth = 10
learning_rate = 0.2
xgboost_model = XGBClassifier(enable_categorical=True, random_state=42, scale_pos_weight=scale_pos_weight, max_depth=max_depth, learning_rate=learning_rate)
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
cv_scores = cross_val_score(xgboost_model, X, y, cv=skf, scoring='f1')
print(f'Cross-validated F1 scores: {cv_scores}')
print(f'Mean F1 score: {cv_scores.mean()}')

Cross-validated F1 scores: [0.69981499 0.7103193  0.69055375 0.71348837 0.70242775]
Mean F1 score: 0.703320829286399

### Tuning with GridSearchCV

Use the code cell below to set up your parameter grid and run GridSearchCV with your preferred model from above. You should tune 4-5 hyperparameters utilizing cross validation. Train a final model using the best hyperparameters and report your model performance.

In [12]:
# your code here add verbose=1 to see the progress
param_grid = {
    'scale_pos_weight': [1.0, 2.0, 3.0, 4.0],
    'max_depth': [3, 4, 5],
    'learning_rate': [0.1, 0.2, 0.3],
    'n_estimators': [100, 200],
    'gamma': [0, 0.1, 0.2, 0.3]
  
}

xgb_grid = XGBClassifier(enable_categorical=True, random_state=42)
grid_search = GridSearchCV(xgb_grid, param_grid, cv=skf, scoring='f1', verbose=2)
grid_search.fit(X_train, y_train)

print(f'Best parameters from GridSearchCV: {grid_search.best_params_}')
print(f'Best F1 score from GridSearchCV: {grid_search.best_score_}')

xgb_grid_best = XGBClassifier(enable_categorical=True, random_state=42, **grid_search.best_params_)
xgb_grid_best.fit(X_train, y_train)

Fitting 5 folds for each of 288 candidates, totalling 1440 fits
[CV] END gamma=0, learning_rate=0.1, max_depth=3, n_estimators=100, scale_pos_weight=1.0; total time=   0.1s
[CV] END gamma=0, learning_rate=0.1, max_depth=3, n_estimators=100, scale_pos_weight=1.0; total time=   0.1s
[CV] END gamma=0, learning_rate=0.1, max_depth=3, n_estimators=100, scale_pos_weight=1.0; total time=   0.1s
[CV] END gamma=0, learning_rate=0.1, max_depth=3, n_estimators=100, scale_pos_weight=1.0; total time=   0.1s
[CV] END gamma=0, learning_rate=0.1, max_depth=3, n_estimators=100, scale_pos_weight=1.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=3, n_estimators=100, scale_pos_weight=2.0; total time=   0.1s
[CV] END gamma=0, learning_rate=0.1, max_depth=3, n_estimators=100, scale_pos_weight=2.0; total time=   0.1s
[CV] END gamma=0, learning_rate=0.1, max_depth=3, n_estimators=100, scale_pos_weight=2.0; total time=   0.1s
[CV] END gamma=0, learning_rate=0.1, max_depth=3, n_estimators=100, scale_pos_weight=2.0; total time=   0.1s
[CV] END gamma=0, learning_rate=0.1, max_depth=3, n_estimators=100, scale_pos_weight=2.0; total time=   0.1s
[CV] END gamma=0, learning_rate=0.1, max_depth=3, n_estimators=100, scale_pos_weight=3.0; total time=   0.1s
[CV] END gamma=0, learning_rate=0.1, max_depth=3, n_estimators=100, scale_pos_weight=3.0; total time=   0.1s
[CV] END gamma=0, learning_rate=0.1, max_depth=3, n_estimators=100, scale_pos_weight=3.0; total time=   0.1s
[CV] END gamma=0, learning_rate=0.1, max_depth=3, n_estimators=100, scale_pos_weight=3.0; total time=   0.1s
[CV] END gamma=0, learning_rate=0.1, max_depth=3, n_estimators=100, scale_pos_weight=3.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=3, n_estimators=100, scale_pos_weight=4.0; total time=   0.1s
[CV] END gamma=0, learning_rate=0.1, max_depth=3, n_estimators=100, scale_pos_weight=4.0; total time=   0.1s
[CV] END gamma=0, learning_rate=0.1, max_depth=3, n_estimators=100, scale_pos_weight=4.0; total time=   0.1s
[CV] END gamma=0, learning_rate=0.1, max_depth=3, n_estimators=100, scale_pos_weight=4.0; total time=   0.1s
[CV] END gamma=0, learning_rate=0.1, max_depth=3, n_estimators=100, scale_pos_weight=4.0; total time=   0.1s
[CV] END gamma=0, learning_rate=0.1, max_depth=3, n_estimators=200, scale_pos_weight=1.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=3, n_estimators=200, scale_pos_weight=1.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=3, n_estimators=200, scale_pos_weight=1.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=3, n_estimators=200, scale_pos_weight=1.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=3, n_estimators=200, scale_pos_weight=1.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=3, n_estimators=200, scale_pos_weight=2.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=3, n_estimators=200, scale_pos_weight=2.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=3, n_estimators=200, scale_pos_weight=2.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=3, n_estimators=200, scale_pos_weight=2.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=3, n_estimators=200, scale_pos_weight=2.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=3, n_estimators=200, scale_pos_weight=3.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=3, n_estimators=200, scale_pos_weight=3.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=3, n_estimators=200, scale_pos_weight=3.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=3, n_estimators=200, scale_pos_weight=3.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=3, n_estimators=200, scale_pos_weight=3.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=3, n_estimators=200, scale_pos_weight=4.0; total time=   0.3s
[CV] END gamma=0, learning_rate=0.1, max_depth=3, n_estimators=200, scale_pos_weight=4.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=3, n_estimators=200, scale_pos_weight=4.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=3, n_estimators=200, scale_pos_weight=4.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=3, n_estimators=200, scale_pos_weight=4.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=4, n_estimators=100, scale_pos_weight=1.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=4, n_estimators=100, scale_pos_weight=1.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=4, n_estimators=100, scale_pos_weight=1.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=4, n_estimators=100, scale_pos_weight=1.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=4, n_estimators=100, scale_pos_weight=1.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=4, n_estimators=100, scale_pos_weight=2.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=4, n_estimators=100, scale_pos_weight=2.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=4, n_estimators=100, scale_pos_weight=2.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=4, n_estimators=100, scale_pos_weight=2.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=4, n_estimators=100, scale_pos_weight=2.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=4, n_estimators=100, scale_pos_weight=3.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=4, n_estimators=100, scale_pos_weight=3.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=4, n_estimators=100, scale_pos_weight=3.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=4, n_estimators=100, scale_pos_weight=3.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=4, n_estimators=100, scale_pos_weight=3.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=4, n_estimators=100, scale_pos_weight=4.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=4, n_estimators=100, scale_pos_weight=4.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=4, n_estimators=100, scale_pos_weight=4.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=4, n_estimators=100, scale_pos_weight=4.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=4, n_estimators=100, scale_pos_weight=4.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=4, n_estimators=200, scale_pos_weight=1.0; total time=   0.3s
[CV] END gamma=0, learning_rate=0.1, max_depth=4, n_estimators=200, scale_pos_weight=1.0; total time=   0.3s
[CV] END gamma=0, learning_rate=0.1, max_depth=4, n_estimators=200, scale_pos_weight=1.0; total time=   0.3s
[CV] END gamma=0, learning_rate=0.1, max_depth=4, n_estimators=200, scale_pos_weight=1.0; total time=   0.3s
[CV] END gamma=0, learning_rate=0.1, max_depth=4, n_estimators=200, scale_pos_weight=1.0; total time=   0.3s
[CV] END gamma=0, learning_rate=0.1, max_depth=4, n_estimators=200, scale_pos_weight=2.0; total time=   0.3s
[CV] END gamma=0, learning_rate=0.1, max_depth=4, n_estimators=200, scale_pos_weight=2.0; total time=   0.3s
[CV] END gamma=0, learning_rate=0.1, max_depth=4, n_estimators=200, scale_pos_weight=2.0; total time=   0.3s
[CV] END gamma=0, learning_rate=0.1, max_depth=4, n_estimators=200, scale_pos_weight=2.0; total time=   0.3s
[CV] END gamma=0, learning_rate=0.1, max_depth=4, n_estimators=200, scale_pos_weight=2.0; total time=   0.3s
[CV] END gamma=0, learning_rate=0.1, max_depth=4, n_estimators=200, scale_pos_weight=3.0; total time=   0.3s
[CV] END gamma=0, learning_rate=0.1, max_depth=4, n_estimators=200, scale_pos_weight=3.0; total time=   0.3s
[CV] END gamma=0, learning_rate=0.1, max_depth=4, n_estimators=200, scale_pos_weight=3.0; total time=   0.3s
[CV] END gamma=0, learning_rate=0.1, max_depth=4, n_estimators=200, scale_pos_weight=3.0; total time=   0.3s
[CV] END gamma=0, learning_rate=0.1, max_depth=4, n_estimators=200, scale_pos_weight=3.0; total time=   0.3s
[CV] END gamma=0, learning_rate=0.1, max_depth=4, n_estimators=200, scale_pos_weight=4.0; total time=   0.3s
[CV] END gamma=0, learning_rate=0.1, max_depth=4, n_estimators=200, scale_pos_weight=4.0; total time=   0.3s
[CV] END gamma=0, learning_rate=0.1, max_depth=4, n_estimators=200, scale_pos_weight=4.0; total time=   0.3s
[CV] END gamma=0, learning_rate=0.1, max_depth=4, n_estimators=200, scale_pos_weight=4.0; total time=   0.3s
[CV] END gamma=0, learning_rate=0.1, max_depth=4, n_estimators=200, scale_pos_weight=4.0; total time=   0.3s
[CV] END gamma=0, learning_rate=0.1, max_depth=5, n_estimators=100, scale_pos_weight=1.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=5, n_estimators=100, scale_pos_weight=1.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=5, n_estimators=100, scale_pos_weight=1.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=5, n_estimators=100, scale_pos_weight=1.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=5, n_estimators=100, scale_pos_weight=1.0; total time=   0.3s
[CV] END gamma=0, learning_rate=0.1, max_depth=5, n_estimators=100, scale_pos_weight=2.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=5, n_estimators=100, scale_pos_weight=2.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=5, n_estimators=100, scale_pos_weight=2.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=5, n_estimators=100, scale_pos_weight=2.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=5, n_estimators=100, scale_pos_weight=2.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=5, n_estimators=100, scale_pos_weight=3.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=5, n_estimators=100, scale_pos_weight=3.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=5, n_estimators=100, scale_pos_weight=3.0; total time=   0.3s
[CV] END gamma=0, learning_rate=0.1, max_depth=5, n_estimators=100, scale_pos_weight=3.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=5, n_estimators=100, scale_pos_weight=3.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=5, n_estimators=100, scale_pos_weight=4.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=5, n_estimators=100, scale_pos_weight=4.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=5, n_estimators=100, scale_pos_weight=4.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=5, n_estimators=100, scale_pos_weight=4.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=5, n_estimators=100, scale_pos_weight=4.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.1, max_depth=5, n_estimators=200, scale_pos_weight=1.0; total time=   0.4s
[CV] END gamma=0, learning_rate=0.1, max_depth=5, n_estimators=200, scale_pos_weight=1.0; total time=   0.4s
[CV] END gamma=0, learning_rate=0.1, max_depth=5, n_estimators=200, scale_pos_weight=1.0; total time=   0.4s
[CV] END gamma=0, learning_rate=0.1, max_depth=5, n_estimators=200, scale_pos_weight=1.0; total time=   0.4s
[CV] END gamma=0, learning_rate=0.1, max_depth=5, n_estimators=200, scale_pos_weight=1.0; total time=   0.4s
[CV] END gamma=0, learning_rate=0.1, max_depth=5, n_estimators=200, scale_pos_weight=2.0; total time=   0.4s
[CV] END gamma=0, learning_rate=0.1, max_depth=5, n_estimators=200, scale_pos_weight=2.0; total time=   0.4s
[CV] END gamma=0, learning_rate=0.1, max_depth=5, n_estimators=200, scale_pos_weight=2.0; total time=   0.4s
[CV] END gamma=0, learning_rate=0.1, max_depth=5, n_estimators=200, scale_pos_weight=2.0; total time=   0.4s
[CV] END gamma=0, learning_rate=0.1, max_depth=5, n_estimators=200, scale_pos_weight=2.0; total time=   0.4s
[CV] END gamma=0, learning_rate=0.1, max_depth=5, n_estimators=200, scale_pos_weight=3.0; total time=   0.4s
[CV] END gamma=0, learning_rate=0.1, max_depth=5, n_estimators=200, scale_pos_weight=3.0; total time=   0.4s
[CV] END gamma=0, learning_rate=0.1, max_depth=5, n_estimators=200, scale_pos_weight=3.0; total time=   0.6s
[CV] END gamma=0, learning_rate=0.1, max_depth=5, n_estimators=200, scale_pos_weight=3.0; total time=   0.7s
[CV] END gamma=0, learning_rate=0.1, max_depth=5, n_estimators=200, scale_pos_weight=3.0; total time=   0.3s
[CV] END gamma=0, learning_rate=0.1, max_depth=5, n_estimators=200, scale_pos_weight=4.0; total time=   0.3s
[CV] END gamma=0, learning_rate=0.1, max_depth=5, n_estimators=200, scale_pos_weight=4.0; total time=   0.4s
[CV] END gamma=0, learning_rate=0.1, max_depth=5, n_estimators=200, scale_pos_weight=4.0; total time=   0.4s
[CV] END gamma=0, learning_rate=0.1, max_depth=5, n_estimators=200, scale_pos_weight=4.0; total time=   0.4s
[CV] END gamma=0, learning_rate=0.1, max_depth=5, n_estimators=200, scale_pos_weight=4.0; total time=   0.4s
[CV] END gamma=0, learning_rate=0.2, max_depth=3, n_estimators=100, scale_pos_weight=1.0; total time=   0.1s
[CV] END gamma=0, learning_rate=0.2, max_depth=3, n_estimators=100, scale_pos_weight=1.0; total time=   0.1s
[CV] END gamma=0, learning_rate=0.2, max_depth=3, n_estimators=100, scale_pos_weight=1.0; total time=   0.1s
[CV] END gamma=0, learning_rate=0.2, max_depth=3, n_estimators=100, scale_pos_weight=1.0; total time=   0.1s
[CV] END gamma=0, learning_rate=0.2, max_depth=3, n_estimators=100, scale_pos_weight=1.0; total time=   0.1s
[CV] END gamma=0, learning_rate=0.2, max_depth=3, n_estimators=100, scale_pos_weight=2.0; total time=   0.1s
[CV] END gamma=0, learning_rate=0.2, max_depth=3, n_estimators=100, scale_pos_weight=2.0; total time=   0.1s
[CV] END gamma=0, learning_rate=0.2, max_depth=3, n_estimators=100, scale_pos_weight=2.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.2, max_depth=3, n_estimators=100, scale_pos_weight=2.0; total time=   0.1s
[CV] END gamma=0, learning_rate=0.2, max_depth=3, n_estimators=100, scale_pos_weight=2.0; total time=   0.1s
[CV] END gamma=0, learning_rate=0.2, max_depth=3, n_estimators=100, scale_pos_weight=3.0; total time=   0.1s
[CV] END gamma=0, learning_rate=0.2, max_depth=3, n_estimators=100, scale_pos_weight=3.0; total time=   0.1s
[CV] END gamma=0, learning_rate=0.2, max_depth=3, n_estimators=100, scale_pos_weight=3.0; total time=   0.1s
[CV] END gamma=0, learning_rate=0.2, max_depth=3, n_estimators=100, scale_pos_weight=3.0; total time=   0.1s
[CV] END gamma=0, learning_rate=0.2, max_depth=3, n_estimators=100, scale_pos_weight=3.0; total time=   0.1s
[CV] END gamma=0, learning_rate=0.2, max_depth=3, n_estimators=100, scale_pos_weight=4.0; total time=   0.1s
[CV] END gamma=0, learning_rate=0.2, max_depth=3, n_estimators=100, scale_pos_weight=4.0; total time=   0.1s
[CV] END gamma=0, learning_rate=0.2, max_depth=3, n_estimators=100, scale_pos_weight=4.0; total time=   0.1s
[CV] END gamma=0, learning_rate=0.2, max_depth=3, n_estimators=100, scale_pos_weight=4.0; total time=   0.1s
[CV] END gamma=0, learning_rate=0.2, max_depth=3, n_estimators=100, scale_pos_weight=4.0; total time=   0.1s
[CV] END gamma=0, learning_rate=0.2, max_depth=3, n_estimators=200, scale_pos_weight=1.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.2, max_depth=3, n_estimators=200, scale_pos_weight=1.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.2, max_depth=3, n_estimators=200, scale_pos_weight=1.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.2, max_depth=3, n_estimators=200, scale_pos_weight=1.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.2, max_depth=3, n_estimators=200, scale_pos_weight=1.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.2, max_depth=3, n_estimators=200, scale_pos_weight=2.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.2, max_depth=3, n_estimators=200, scale_pos_weight=2.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.2, max_depth=3, n_estimators=200, scale_pos_weight=2.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.2, max_depth=3, n_estimators=200, scale_pos_weight=2.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.2, max_depth=3, n_estimators=200, scale_pos_weight=2.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.2, max_depth=3, n_estimators=200, scale_pos_weight=3.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.2, max_depth=3, n_estimators=200, scale_pos_weight=3.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.2, max_depth=3, n_estimators=200, scale_pos_weight=3.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.2, max_depth=3, n_estimators=200, scale_pos_weight=3.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.2, max_depth=3, n_estimators=200, scale_pos_weight=3.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.2, max_depth=3, n_estimators=200, scale_pos_weight=4.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.2, max_depth=3, n_estimators=200, scale_pos_weight=4.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.2, max_depth=3, n_estimators=200, scale_pos_weight=4.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.2, max_depth=3, n_estimators=200, scale_pos_weight=4.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.2, max_depth=3, n_estimators=200, scale_pos_weight=4.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.2, max_depth=4, n_estimators=100, scale_pos_weight=1.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.2, max_depth=4, n_estimators=100, scale_pos_weight=1.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.2, max_depth=4, n_estimators=100, scale_pos_weight=1.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.2, max_depth=4, n_estimators=100, scale_pos_weight=1.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.2, max_depth=4, n_estimators=100, scale_pos_weight=1.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.2, max_depth=4, n_estimators=100, scale_pos_weight=2.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.2, max_depth=4, n_estimators=100, scale_pos_weight=2.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.2, max_depth=4, n_estimators=100, scale_pos_weight=2.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.2, max_depth=4, n_estimators=100, scale_pos_weight=2.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.2, max_depth=4, n_estimators=100, scale_pos_weight=2.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.2, max_depth=4, n_estimators=100, scale_pos_weight=3.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.2, max_depth=4, n_estimators=100, scale_pos_weight=3.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.2, max_depth=4, n_estimators=100, scale_pos_weight=3.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.2, max_depth=4, n_estimators=100, scale_pos_weight=3.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.2, max_depth=4, n_estimators=100, scale_pos_weight=3.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.2, max_depth=4, n_estimators=100, scale_pos_weight=4.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.2, max_depth=4, n_estimators=100, scale_pos_weight=4.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.2, max_depth=4, n_estimators=100, scale_pos_weight=4.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.2, max_depth=4, n_estimators=100, scale_pos_weight=4.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.2, max_depth=4, n_estimators=100, scale_pos_weight=4.0; total time=   0.2s
[CV] END gamma=0, learning_rate=0.2, max_depth=4, n_estimators=200, scale_pos_weight=1.0; total time=   0.4s
[CV] END gamma=0, learning_rate=0.2, max_depth=4, n_estimators=200, scale_pos_weight=1.0; total time=   0.3s

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=0.3, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.2, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=100,
              n_jobs=None, num_parallel_tree=None, ...)

### Tuning with RandomizedSearchCV

Using the code cell below as a starting point, tune your preferred model from above. Tune the same 4-5 hyperparameters from above utilizing cross validation. Train a final model using the best hyperparameters and report your model performance.

In [13]:
# tuning xgboost classifier with RandomizedSearchCV (tune more parameters than shown here)
param_dist = {
    'scale_pos_weight': [1.0, 2.0, 3.0, 4.0],
    'max_depth': [3, 4, 5],
    'learning_rate': [0.1, 0.2, 0.3],
    'n_estimators': [100, 200],
    'gamma': [0, 0.1, 0.2, 0.3]
}

# replace this placeholder model with your preferred model from above

xgb_tuned = RandomizedSearchCV(XGBClassifier(random_state=42, enable_categorical=True),
                                param_distributions=param_dist, n_iter=20, cv=skf, scoring='f1', random_state=42)
xgb_tuned.fit(X_train, y_train)
print(f'Best parameters from RandomizedSearchCV: {xgb_tuned.best_params_}')
print(f'Best F1 score from RandomizedSearchCV: {xgb_tuned.best_score_}')   

# build your preferred model from above using best parameters from your RandomizedSearchCV
# and evaluate on the test set

xgb_tuned_best = XGBClassifier(random_state=42, scale_pos_weight=xgb_tuned.best_params_['scale_pos_weight'], 
                                max_depth=xgb_tuned.best_params_['max_depth'], 
                                learning_rate=xgb_tuned.best_params_['learning_rate'], 
                                n_estimators=xgb_tuned.best_params_['n_estimators'],
                                gamma=xgb_tuned.best_params_['gamma'],
                                enable_categorical=True)
xgb_tuned_best.fit(X_train, y_train)
y_pred_random = xgb_tuned_best.predict(X_test)
print(f'Classification report for RandomizedSearchCV-tuned model:\n{classification_report(y_test, y_pred_random)}')

Best parameters from RandomizedSearchCV: {'scale_pos_weight': 2.0, 'n_estimators': 200, 'max_depth': 5, 'learning_rate': 0.1, 'gamma': 0.3}
Best F1 score from RandomizedSearchCV: 0.7286579570879569
Classification report for RandomizedSearchCV-tuned model:
              precision    recall  f1-score   support

           0       0.93      0.88      0.91      7431
           1       0.68      0.79      0.73      2338

    accuracy                           0.86      9769
   macro avg       0.80      0.84      0.82      9769
weighted avg       0.87      0.86      0.86      9769

### Tuning with Optuna

Using the code cell below as a starting point, tune your preferred model from above. You should tune the same 4-5 parameters as above using cross validation. Train a final model using the best hyperparameters and report your model performance.

In [14]:
# tuning with Optuna (tune more parameters than shown here)
def objective(trial):
    scale_pos_weight = trial.suggest_float('scale_pos_weight', 1.0, 10.0)
    max_depth = trial.suggest_int('max_depth', 3, 10)
    learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3)
    n_estimators = trial.suggest_int('n_estimators', 100, 200)
    gamma = trial.suggest_float('gamma', 0, 0.3)
    
    # replace this placeholder model with your preferred model from above
    
    xgb_optuna = XGBClassifier(random_state=42, scale_pos_weight=scale_pos_weight, 
                               max_depth=max_depth,  learning_rate=learning_rate, enable_categorical=True)
    
    cv_scores = cross_val_score(xgb_optuna, X, y, cv=skf, scoring='f1')
    return cv_scores.mean()

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=20, show_progress_bar=True)

print(f'Best parameters from Optuna: {study.best_params}')
print(f'Best F1 score from Optuna: {study.best_value}')

# build preferred model from above with best parameters from Optuna and evaluate on the test set
xgb_optuna_best = XGBClassifier(random_state=42, scale_pos_weight=study.best_params['scale_pos_weight'], 
                                  max_depth=study.best_params['max_depth'], 
                                  learning_rate=study.best_params['learning_rate'], 
                                  enable_categorical=True)
xgb_optuna_best.fit(X_train, y_train)
y_pred_optuna = xgb_optuna_best.predict(X_test)
print(f'Classification report for Optuna-tuned model:\n{classification_report(y_test, y_pred_optuna)}')

[I 2026-04-15 21:33:58,180] A new study created in memory with name: no-name-2cca06b6-232e-4573-8dac-b145c5fe492e
Best trial: 0. Best value: 0.615411:   5%|▌         | 1/20 [00:00<00:16,  1.16it/s]

[I 2026-04-15 21:33:59,057] Trial 0 finished with value: 0.615411310314466 and parameters: {'scale_pos_weight': 9.364235120434534, 'max_depth': 3, 'learning_rate': 0.06306185366406364, 'n_estimators': 106, 'gamma': 0.27827313067261916}. Best is trial 0 with value: 0.615411310314466.

Best trial: 1. Best value: 0.679033:  10%|█         | 2/20 [00:02<00:19,  1.09s/it]

[I 2026-04-15 21:34:00,301] Trial 1 finished with value: 0.6790326428676471 and parameters: {'scale_pos_weight': 7.871170685136163, 'max_depth': 6, 'learning_rate': 0.29962160805546606, 'n_estimators': 164, 'gamma': 0.0919380909698861}. Best is trial 1 with value: 0.6790326428676471.

Best trial: 2. Best value: 0.706506:  15%|█▌        | 3/20 [00:04<00:26,  1.57s/it]

[I 2026-04-15 21:34:02,446] Trial 2 finished with value: 0.7065055285255035 and parameters: {'scale_pos_weight': 4.119422559781027, 'max_depth': 10, 'learning_rate': 0.15134959195512993, 'n_estimators': 166, 'gamma': 0.006825185661463384}. Best is trial 2 with value: 0.7065055285255035.

Best trial: 3. Best value: 0.711996:  20%|██        | 4/20 [00:05<00:19,  1.25s/it]

[I 2026-04-15 21:34:03,199] Trial 3 finished with value: 0.7119963218378823 and parameters: {'scale_pos_weight': 2.339091033893548, 'max_depth': 3, 'learning_rate': 0.10163053074460755, 'n_estimators': 165, 'gamma': 0.13117861141780288}. Best is trial 3 with value: 0.7119963218378823.

Best trial: 3. Best value: 0.711996:  25%|██▌       | 5/20 [00:07<00:25,  1.71s/it]

[I 2026-04-15 21:34:05,741] Trial 4 finished with value: 0.7114974235871551 and parameters: {'scale_pos_weight': 2.779859832041051, 'max_depth': 10, 'learning_rate': 0.03140302410836617, 'n_estimators': 139, 'gamma': 0.24115023451453815}. Best is trial 3 with value: 0.7119963218378823.

Best trial: 5. Best value: 0.71255:  30%|███       | 6/20 [00:08<00:21,  1.55s/it]

[I 2026-04-15 21:34:06,985] Trial 5 finished with value: 0.7125501121943881 and parameters: {'scale_pos_weight': 3.370490259607098, 'max_depth': 6, 'learning_rate': 0.1636132636519231, 'n_estimators': 125, 'gamma': 0.14306582570431092}. Best is trial 5 with value: 0.7125501121943881.

Best trial: 5. Best value: 0.71255:  35%|███▌      | 7/20 [00:10<00:20,  1.61s/it]

[I 2026-04-15 21:34:08,706] Trial 6 finished with value: 0.6851881261759405 and parameters: {'scale_pos_weight': 6.877361954468794, 'max_depth': 8, 'learning_rate': 0.1377491546221682, 'n_estimators': 125, 'gamma': 0.05637634030832321}. Best is trial 5 with value: 0.7125501121943881.

Best trial: 5. Best value: 0.71255:  40%|████      | 8/20 [00:11<00:18,  1.52s/it]

[I 2026-04-15 21:34:10,040] Trial 7 finished with value: 0.6656879363945676 and parameters: {'scale_pos_weight': 8.133381047791067, 'max_depth': 6, 'learning_rate': 0.09740077415378932, 'n_estimators': 171, 'gamma': 0.23221206812940764}. Best is trial 5 with value: 0.7125501121943881.

Best trial: 8. Best value: 0.713746:  45%|████▌     | 9/20 [00:13<00:15,  1.44s/it]

[I 2026-04-15 21:34:11,303] Trial 8 finished with value: 0.7137459008615781 and parameters: {'scale_pos_weight': 3.229042814199495, 'max_depth': 6, 'learning_rate': 0.29974506411401414, 'n_estimators': 178, 'gamma': 0.23337827959182672}. Best is trial 8 with value: 0.7137459008615781.

Best trial: 8. Best value: 0.713746:  50%|█████     | 10/20 [00:14<00:15,  1.52s/it]

[I 2026-04-15 21:34:13,015] Trial 9 finished with value: 0.6985736918407508 and parameters: {'scale_pos_weight': 5.162037705055875, 'max_depth': 8, 'learning_rate': 0.27037107571832086, 'n_estimators': 174, 'gamma': 0.11277742306254913}. Best is trial 8 with value: 0.7137459008615781.

Best trial: 10. Best value: 0.729967:  55%|█████▌    | 11/20 [00:15<00:11,  1.33s/it]

[I 2026-04-15 21:34:13,903] Trial 10 finished with value: 0.729966711549908 and parameters: {'scale_pos_weight': 1.4938115209630496, 'max_depth': 4, 'learning_rate': 0.2356521229322022, 'n_estimators': 198, 'gamma': 0.18855239532975565}. Best is trial 10 with value: 0.729966711549908.

Best trial: 10. Best value: 0.729967:  60%|██████    | 12/20 [00:16<00:09,  1.20s/it]

[I 2026-04-15 21:34:14,804] Trial 11 finished with value: 0.713787530449982 and parameters: {'scale_pos_weight': 1.0349933622757355, 'max_depth': 4, 'learning_rate': 0.23051410472376205, 'n_estimators': 196, 'gamma': 0.2002417878639604}. Best is trial 10 with value: 0.729966711549908.

Best trial: 10. Best value: 0.729967:  65%|██████▌   | 13/20 [00:17<00:07,  1.11s/it]

[I 2026-04-15 21:34:15,724] Trial 12 finished with value: 0.7155898245151974 and parameters: {'scale_pos_weight': 1.0798599841608159, 'max_depth': 4, 'learning_rate': 0.22038757875107026, 'n_estimators': 196, 'gamma': 0.17588499646929467}. Best is trial 10 with value: 0.729966711549908.

Best trial: 10. Best value: 0.729967:  70%|███████   | 14/20 [00:18<00:06,  1.07s/it]

[I 2026-04-15 21:34:16,691] Trial 13 finished with value: 0.7201393177083937 and parameters: {'scale_pos_weight': 1.1679461273821399, 'max_depth': 4, 'learning_rate': 0.2129657038701078, 'n_estimators': 199, 'gamma': 0.17665234097956128}. Best is trial 10 with value: 0.729966711549908.

Best trial: 10. Best value: 0.729967:  75%|███████▌  | 15/20 [00:19<00:05,  1.03s/it]

[I 2026-04-15 21:34:17,631] Trial 14 finished with value: 0.7298230503050231 and parameters: {'scale_pos_weight': 1.9151581563162874, 'max_depth': 4, 'learning_rate': 0.21071663501591795, 'n_estimators': 187, 'gamma': 0.183844703848136}. Best is trial 10 with value: 0.729966711549908.

Best trial: 10. Best value: 0.729967:  80%|████████  | 16/20 [00:20<00:04,  1.07s/it]

[I 2026-04-15 21:34:18,792] Trial 15 finished with value: 0.6920288723204675 and parameters: {'scale_pos_weight': 5.051416271782386, 'max_depth': 5, 'learning_rate': 0.19177242962234173, 'n_estimators': 187, 'gamma': 0.28946711842018225}. Best is trial 10 with value: 0.729966711549908.

Best trial: 10. Best value: 0.729967:  85%|████████▌ | 17/20 [00:21<00:03,  1.10s/it]

[I 2026-04-15 21:34:19,975] Trial 16 finished with value: 0.7263075155602421 and parameters: {'scale_pos_weight': 2.1410279806861294, 'max_depth': 5, 'learning_rate': 0.24843271622460453, 'n_estimators': 151, 'gamma': 0.1851044832586215}. Best is trial 10 with value: 0.729966711549908.

Best trial: 10. Best value: 0.729967:  90%|█████████ | 18/20 [00:23<00:02,  1.31s/it]

[I 2026-04-15 21:34:21,767] Trial 17 finished with value: 0.706872765156122 and parameters: {'scale_pos_weight': 4.185051395907226, 'max_depth': 8, 'learning_rate': 0.2604684945228291, 'n_estimators': 184, 'gamma': 0.07266551681154702}. Best is trial 10 with value: 0.729966711549908.

Best trial: 10. Best value: 0.729967:  95%|█████████▌| 19/20 [00:24<00:01,  1.15s/it]

[I 2026-04-15 21:34:22,539] Trial 18 finished with value: 0.7234123297523167 and parameters: {'scale_pos_weight': 1.9326373605340885, 'max_depth': 3, 'learning_rate': 0.17322916165026353, 'n_estimators': 155, 'gamma': 0.21333330565526296}. Best is trial 10 with value: 0.729966711549908.

Best trial: 10. Best value: 0.729967: 100%|██████████| 20/20 [00:25<00:00,  1.27s/it]

[I 2026-04-15 21:34:23,643] Trial 19 finished with value: 0.6822144707141631 and parameters: {'scale_pos_weight': 6.264703283588426, 'max_depth': 5, 'learning_rate': 0.1979182951503735, 'n_estimators': 181, 'gamma': 0.2696900011937085}. Best is trial 10 with value: 0.729966711549908.
Best parameters from Optuna: {'scale_pos_weight': 1.4938115209630496, 'max_depth': 4, 'learning_rate': 0.2356521229322022, 'n_estimators': 198, 'gamma': 0.18855239532975565}
Best F1 score from Optuna: 0.729966711549908
Classification report for Optuna-tuned model:
              precision    recall  f1-score   support

           0       0.92      0.91      0.92      7431
           1       0.73      0.74      0.73      2338

    accuracy                           0.87      9769
   macro avg       0.82      0.83      0.82      9769
weighted avg       0.87      0.87      0.87      9769

### Tuning results

In the markdown cell below describe your experience tuning with the different methods. Which produced the best results? Which do you prefer?

With the different tuning methods Grid search took the longest by far. Then random was next followed by Optuna. Grid search had a better score then random but optuna had the best scores out of all of the models. The differences were pretty small however the timing difference between grid search and optuna was huge. Clearly optuna is the best option as it had the best scores and the shortest tuning time.